### ISSUE TITLE
Error after last update "_angularFix2.default.config"

### ISSUE THREAD

**Issue by maku** [formly-js/angular-formly-templates-material#5]
When my app runs I get an error "_angularFix2.default.config is not a function:

```
_angularFix2.default.config is not a function
    at http://localhost:9000/jspm_packages/github/formly-js/angular-formly-templates-material@master/dist/angular-formly-templates-material.js:154:35
    at Object.forEach (http://localhost:9000/jspm_packages/github/angular/bower-angular@1.4.1/angular.js:339:20)
    at Object.<anonymous> (http://localhost:9000/jspm_packages/github/formly-js/angular-formly-templates-material@master/dist/angular-formly-templates-material.js:153:26)
    at __webpack_require__ (http://localhost:9000/jspm_packages/github/formly-js/angular-formly-templates-material@master/dist/angular-formly-templates-material.js:32:30)
    at Object.defineProperty.value (http://localhost:9000/jspm_packages/github/formly-js/angular-formly-templates-material@master/dist/angular-formly-templates-material.js:67:21)
    at __webpack_require__ (http://localhost:9000/jspm_packages/github/formly-js/angular-formly-templates-material@master/dist/angular-formly-templates-material.js:32:30)
    at Object.defineProperty.value (http://localhost:9000/jspm_packages/github/formly-js/angular-formly-templates-material@master/dist/angular-formly-templates-material.js:52:18)
    at Function.<anonymous> (http://localhost:9000/jspm_packages/github/formly-js/angular-formly-templates-material@master/dist/angular-formly-templates-material.js:55:10)
    at $__global.upgradeSystemLoader.c.execute (http://localhost:9000/jspm_packages/system.js:1:14731)
    at f (http://localhost:9000/jspm_packages/system.js:1:5970)
```

**Comment by kentcdodds** [comment]
It's not ready for development. Still a work in progress. Sorry.
